server:
  port: 8004
spring:
    application:
      name: config-server
    cloud:
        config:
          server:
            git:
              uri: https://github.com/vipchadchen/spring-cloud-parent.git
              username: chgj121@163.com
              password: Gi196031
              searchPaths: 'config-repo'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/